# Generated by Django 3.2.7 on 2021-09-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caucaSostenible', '0003_undertaking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=300)),
                ('imgURL', models.CharField(max_length=300)),
            ],
        ),
    ]
