# Generated by Django 3.2.7 on 2021-09-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caucaSostenible', '0006_undertaking_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undertaking',
            name='imgURL',
            field=models.CharField(max_length=300),
        ),
    ]
